# Generated by Django 3.2.12 on 2022-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=300)),
                ('policestation', models.CharField(max_length=300)),
                ('market', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ImportantInfo',
            },
        ),
    ]
