# Generated by Django 3.2.12 on 2022-03-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinfo',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.signups'),
        ),
    ]
