# Generated by Django 3.2.12 on 2022-03-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_importantinfo_village'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='importantinfo',
            table='ImportantInfo',
        ),
    ]
