# Generated by Django 3.2.12 on 2022-03-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userimages', models.ImageField(upload_to='profiles/')),
                ('aboutme', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.signups')),
            ],
            options={
                'db_table': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(null=True, upload_to='posts/')),
                ('post_text', models.TextField()),
                ('post_dates', models.DateTimeField(auto_now=True)),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.signups')),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
