# Generated by Django 3.2.12 on 2022-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villagename', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Villages',
            },
        ),
    ]
