# Generated by Django 3.2.12 on 2022-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('passwords', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Signups',
            },
        ),
    ]
